# Generated by Django 4.2.11 on 2024-04-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentHubAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.ManyToManyField(to='RentHubAPI.propertytype'),
        ),
    ]
