# Generated by Django 4.2.11 on 2024-04-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentHubAPI', '0003_remove_feature_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='feature',
            field=models.ManyToManyField(to='RentHubAPI.feature'),
        ),
    ]
