# Generated by Django 4.2.11 on 2024-04-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentHubAPI', '0004_listing_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='feature',
            field=models.ManyToManyField(blank=True, to='RentHubAPI.feature'),
        ),
    ]
